### ISSUE TITLE
Probleme Tutoriel -> Moyen

### ISSUE THREAD

**Issue by samouren** [MathisDetourbet/ocytoIonicApp#10]
A chaque redémarrage, le tutoriel est présent ce qui est assez relou

**Comment by WzrdMatt** [comment]
Vous etes sur de bien avoir appuyé sur terminé à la fin du tuto? Quand je fais le test sur ionic view ca marche normalement.
Si vous voulez je peux faire en sorte que des qu'on affiche la première page du tuto, on considère qu'il est fait et qu'il ne s'ouvrira plus

**Comment by MathisDetourbet** [comment]
@samouren  l'erreur est toujours la ?

**Comment by samouren** [comment]
il n'y a pas eu de maj

**Comment by samouren** [comment]
@
