### ISSUE TITLE
Chargement infini au lancement de l'app

### ISSUE THREAD

**Issue by thiboot** [MathisDetourbet/ocytoIonicApp#12]
L'application charge à l'infini, on ne peux rien faire d'autre

**Comment by thiboot** [comment]
![screenshot 1](https://cloud.githubusercontent.com/assets/1211351/8391713/1c0147ee-1ccc-11e5-87b8-43c9b3e716fe.jpg)

**Comment by MathisDetourbet** [comment]
Resolved !
