### ISSUE TITLE
Chargement carte ANDROID -> Important

### ISSUE THREAD

**Issue by samouren** [MathisDetourbet/ocytoIonicApp#2]
- Chargement de la carte inexistant : Aucun affichage "chargement en cours"
- Problèmes d'affichage des deux icônes "Ma position" et "Centre le plus proche" :

**Comment by MathisDetourbet** [comment]
Oui c'est pareil sur iOS, et c'est, j'ai l'impression, depuis que Thibaut a rajouté son CSS. Je mets Thibaut sur l'issue. Thibaut, si c'est pas toi, met jerem dessus.

Pour les problème d'affichage des boutons c'est une autre issue qu'il faut créer. Je te laisse faire sam

**Comment by samouren** [comment]
Ok je te mets juste la photo 
![screenshot_2015-04-04-22-29-29](https://cloud.githubusercontent.com/assets/11806846/6997125/69ea9fcc-dbaf-11e4-95db-d655082e037b.png)
