### ISSUE TITLE
Problème affichage "chargement de la carte .." -> Important

### ISSUE THREAD

**Issue by samouren** [MathisDetourbet/ocytoIonicApp#3]
Lorsque l'on essaye de charger la carte et que l'on veut revenir en arrière (sur d'autres fonctionnalités), la phrase "Chargement de la carte.." est présent sur toutes les pages et ne veut plus partir.
Il faut donc fermer l'appli et la redémarré pour pouvoir enlever ce beug
![screenshot_2015-04-04-22-26-48](https://cloud.githubusercontent.com/assets/11806846/6997119/162751c8-dbaf-11e4-9eaf-0d420d165c5d.png)
![screenshot_2015-04-04-22-26-40](https://cloud.githubusercontent.com/assets/11806846/6997120/162b840a-dbaf-11e4-9356-7cb7e9831cff.png)

**Comment by MathisDetourbet** [comment]
Est-ce que tu attends que la carte ait fini de se charger avant de passer sur d'autre fonctionnalité ? Si non, le règlement du problème de la carte (issue #2 ) pourrait régler ce problème.

**Comment by samouren** [comment]
La carte ne se charge pas .. Donc je suis revenu en arrière pour avoir accès à d'autres fonctionnalités et voila ce que ça a fait

**Comment by MathisDetourbet** [comment]
Ouais donc si on règle le problème de la carte on règlera cette issue

**Comment by samouren** [comment]
Exact
