### ISSUE TITLE
Problème d'affichage image -> Moyen

### ISSUE THREAD

**Issue by samouren** [MathisDetourbet/ocytoIonicApp#4]
Lorsque l'on ouvre le menu, l'image situé en dessous de "Faire un Don" ne s'affiche pas et se met en lien cassé.
![screenshot_2015-04-04-22-28-56](https://cloud.githubusercontent.com/assets/11806846/6997124/46894e16-dbaf-11e4-8ddf-5b5e70d3bc0e.png)

**Comment by MathisDetourbet** [comment]
Sam le problème est toujours présent ?

**Comment by samouren** [comment]
Rien n'a été mis à jour sur l'appli de mon coté ..

**Comment by samouren** [comment]
la derniere maj à été faite le 7 avril

**Comment by MathisDetourbet** [comment]
Oui j'avais pas uploader l'app... Je viens de le faire. Tu peux regarder à nouveau

**Comment by MathisDetourbet** [comment]
Perso chez moi ca marche par ionic view et meme quand je mets l'application depuis mon mac par usb..
