### ISSUE TITLE
Problème d'affichage Choix -> Faible

### ISSUE THREAD

**Issue by samouren** [MathisDetourbet/ocytoIonicApp#5]
Lorsque l'on veut séléctionner son choix dans "Mes analyses", On voit pas très bien le choix séléctionné.
![screenshot_2015-04-04-22-29-03](https://cloud.githubusercontent.com/assets/11806846/6997134/c0cad8de-dbaf-11e4-974a-9a4072fc7434.png)

**Comment by MathisDetourbet** [comment]
C'est en cours de dév. Je ferme l'issue.
