### ISSUE TITLE
Problème d'affichage Diagramme -> Moyen

### ISSUE THREAD

**Issue by samouren** [MathisDetourbet/ocytoIonicApp#6]
Lorsque j'ai rentré une valeur pour voir l'évolution de mes plaquettes, le diagramme n'a pas bougé.

**Comment by MathisDetourbet** [comment]
Jerem ? T'as vu ce problème ?

**Comment by MathisDetourbet** [comment]
Chez moi ça marche... Sam, teste à nouveau sur la dernière version pour voir. Si ca marche ferme l'issue.
