### ISSUE TITLE
Problème affichage Onglet Carte -> Moyen

### ISSUE THREAD

**Issue by samouren** [MathisDetourbet/ocytoIonicApp#7]
Comme je l'ai dis sur le premier Issue, Il y an problème de taille au niveau de l'affichage des onglets "Ma position" et "Centre le plus proche"
![screenshot_2015-04-04-22-29-29](https://cloud.githubusercontent.com/assets/11806846/6997142/165ce846-dbb0-11e4-954a-f2793e971493.png)

**Comment by cowboyyyy** [comment]
Au sujet de la carte, le fait qu'elle ne s'affiche pas vient du CSS (lorsque j'ajoutais un attribut 'style' dans la balise HTML <map>  la carte s'affichait). 
Pour faire les choses proprement il faut donc que ce 'style' soit intégré dans le fichier sass, je te laisse donc faire Thibault ;)

Pour info : le fichier HTML est geolocation.html, et la balise concernée est <map on-create="mapCreated(map)"></map> ligne 8.
